name: 'Notion Markdown Export'
inputs:
  notion_auth_token:
    description: Auth token of the Notion.
      required: true
    notion_database_id:
      description: ID of the Notion database to be exorted.
      required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: kotlin notion-md-export.main.kts ${{ inputs.notion_auth_token }} ${{ inputs.notion_database_id }}
      shell: bash
